### PR TITLE
🚀 Bootstrap the new core backend

### PR DESCRIPTION
**Pull request by chamerling**
🤘🏻

### CODE REVIEW

**Comment by RomaricMourgues** [comment]
Can you use yarn instead of npm in documentation ? If not can you give me insight of why ? :)

**Comment by RomaricMourgues** [comment]
Conclusion of discussions for now:
- switch to json configuration files (needed for #304)
- try to use yarn instead of npm (if possible)
- add aliases

**Review by RomaricMourgues — APPROVED** [review]
You can squash into feature/2020.Q4.dev then we can start to iterate on it together 🍻

**Comment by chamerling** [comment]
Replaced by #361

**Pull request closed without merging**
